Statefulcomps
akshay-narkar/Calculator-React pull request #5
Opened 2021-07-18 19:30 UTC by akshay-narkar

- App component is converted to a stateful component
- Button panel passes a clickHandler to the buttons
- Event listners are triggered lifting states to stateful App component
- Next value is passed to display to display the result

2021-07-18 23:37 UTC, voscarmv requested changes
# Impressive work.  💻 👀 ✨

## However, there are some changes required 👀 🧰 🔨 🔧
- Please read my comments on how to simplify your solution to the project, and the proper structure of the app component constructor.

### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

2021-07-18 23:37 UTC, voscarmv commented on src/components/App.js
> +  }
- [ ] The project does not require a `decimal` option for the constructor. This only adds unnecessary complexity to the calculation. Please see the example of [my own solution](https://github.com/voscarmv/calculator/blob/development/src/components/App.js#:~:text=extends%20React.Component%20%7B-,constructor(props)%20%7B,%7D,-render()%20%7B) to this project in order to see how you may simplify this part.

2021-07-18 23:37 UTC, voscarmv commented on src/components/App.js
> +
- [ ] Please move all the logic from the calculation to a different file, to keep your code organized. Again, you may follow the example from [my solution](https://github.com/voscarmv/calculator/blob/7aa17ac397ff1a3bf53f335d21568d0524d288e4/src/logic/calculate.js#L3).

2021-07-19 10:28 UTC, addod19 approved these changes
## Status: Approved :trophy:  :balloon: 

Hi @akshay-narkar, congratulations on this milestone so far :smile: Having move the logic into the calculate.js file and the reomval of the decimal in the constructor :+1: I hereby approve the project :smile: Kindly go ahead and merge in to the dev branch :fireworks: 

[Optional]
- The operations sign is not displayed in the calculator display, which is making the app a little awkward. It would be great if we fix that

_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-07-19 10:36 UTC, merged